### ISSUE TITLE
How to use fn instead of control?

### ISSUE THREAD

**Issue by quantonganh** [kkamdooong/hammerspoon-control-hjkl-to-arrow#1]
Since I often use `control-L` to clear the terminal, how can I do the same but using `fn` instead of `control`?

Maybe related:
- https://github.com/Hammerspoon/hammerspoon/issues/689
- https://github.com/Hammerspoon/hammerspoon/issues/922
- https://github.com/Hammerspoon/hammerspoon/issues/975

**Comment by kkamdooong** [comment]
@quantonganh 
`hs.hotkey.bind()` doesn't support 'fn' modifier.

So I suggest a trick.(idea from [here](https://github.com/Hammerspoon/hammerspoon/issues/922#issuecomment-227632370)
First, change your terminal clear terminal shortcut. see [this page](https://support.apple.com/kb/ph18418?locale=en_US)
(below example, I changed terminal clear shortcut to ctrl+cmd+alt+shift + p)
Then, add below code at your init.lua
```
bindFnL = hs.hotkey.bind({}, "l",
    function()
        if hs.eventtap.checkKeyboardModifiers().fn then
            hs.eventtap.event.newKeyEvent({'ctrl', 'alt', 'shift', 'cmd'}, 'p', true):post()
            hs.timer.usleep(1000)
            hs.eventtap.event.newKeyEvent({'ctrl', 'alt', 'shift', 'cmd'}, 'p', false):post()
        else
            bindFnL:disable()
            hs.eventtap.keyStroke({}, "l", 1000)
            bindFnL:enable()
        end
    end
)
```

**Comment by quantonganh** [comment]
@kkamdooong Thanks,

Anyway, https://github.com/Hammerspoon/hammerspoon/issues/1128#issuecomment-266104051 solved my problem.

**Comment by openroc** [comment]
I tried these methods, and seems the problem didn't resolve, and still can not use fn+hjkl for arrow keys

**Comment by openroc** [comment]
btw, ctrl+hjkl works fine~
